### ISSUE TITLE
Unclear documentation?

### ISSUE THREAD

**Issue by avoiding-side-effects** [opal06/zotero2remarkable_bridge#6]
What are we supposed to put for `READ_FOLDER` and `UNREAD_FOLDER`? I've looked through the code a bit, and I think I understand the former but not the latter.

**Comment by opal06** [comment]
`UNREAD_FOLDER` specifies the folder on the reMarkable where files should be placed by the program. The idea is to have this as a kind of inbox on the reMarkable, where new files from Zotero land.
`READ_FOLDER`on the other hand specifies the folder on the reMarkable where read files are placed by the user to be transferred back to Zotero by the program. 
Which folder you pick is entirely up to you, since it can be any folder in the file structure accessible through the device's UI. Starting with empty folders is recommended, though.
I will admit that this is maybe not the most elegant approach, an also that the documentation is lacking. I will look at improving it, but since I have virtually stopped using my reMarkable due to the many limitations it has (and the workaround solutions like this one too), I will need to take a more general look at this script to see if it still works at all.

**Comment by avoiding-side-effects** [comment]
Oh, so for setup you should create a "Zotero" directory on the remarkable, and then create those two folders as subdirectories of `/Zotero/`. This makes a lot more sense. But now I'm doing that and it says the sync was successful but I'm not seeing anything pop up on my RM2?

**Comment by opal06** [comment]
I updated the Readme as I realise I didn't talk enough about the preparations on the RM2 itself.
As to why it doesn't work, just to make sure:
- Check the config.yaml 
- Is rampi working correctly? E.g. do you get output from `rmapi ls`?
- Have you tagged any entries in Zotero as `to_sync`? Maybe start with one entry and see if it is synced
