### ISSUE TITLE
What Webdav are you using?

### ISSUE THREAD

**Issue by mariusmercier** [opal06/zotero2remarkable_bridge#7]
Hi, I tried to set up your script with cloudme.com Webdav service but got an error `RemoteResourceNotFound`, after many trials with the webdavclient3 library I came to the conclusion that CloudMe isn't supported by the library. What Webdav service are you using?

**Comment by opal06** [comment]
I have used and tested Nextcloud's webdav implementation and the one provided by Hetzner's StorageBox product, which both worked as expected. From what I could gather with a quick look, CloudMe seems to offer a standard webdav implementation and should also work. 
Could you please check if you have set the correct URL in the config file? This seems to be `https://webdav.cloudme.com/your_username`. Also, at least with Nextcloud, using 2FA "breaks" webdav login with password (as 2FA can't be used), so an access token is needed.
Also, since it seems unable to actually find the resource, please double check any firewall/DNS/other network configs that might block the script from connecting to the remote.

Other then that, I need to make an account with cloudMe myself and see if I can get more info on the issue, but I won't have much time for that before the weekend, unfortunately.
